[project]
name = "scout"
version = "0.1.1"
description = "An enterprise context agent that navigates your company's knowledge graph"
requires-python = ">=3.12,<4"
readme = "README.md"
license-files = ["LICENSE"]
authors = [{ name = "Agno", email = "hello@agno.com" }]

dependencies = [
  "agno[os,slack]==2.7.0",
  "aiohttp",
  "google-api-python-client",
  "google-auth-httplib2",
  "google-auth-oauthlib",
  "mcp",
  "openai",
  "parallel-web",
  "pgvector",
  "psycopg[binary]",
]

[project.optional-dependencies]
dev = ["mypy", "ruff"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["scout*", "db*", "app*", "evals*"]

[tool.ruff]
line-length = 120
exclude = [".venv*"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]

[tool.mypy]
check_untyped_defs = true
no_implicit_optional = true
warn_unused_configs = true
plugins = ["pydantic.mypy"]
exclude = [".venv*"]

[[tool.mypy.overrides]]
module = [
  "pgvector.*",
  "agno.*",
  "httpx.*",
  "parallel.*",
  "sqlalchemy.*",
  "fastapi.*",
  "googleapiclient.*",
]
ignore_missing_imports = true

[tool.uv.pip]
no-annotate = true
